export default [
  {
    genre: "Hindi",
    image: "Song Images/Sun rha hai na tu.jpg",
    songName: "Sun Rha Hai",
    songId: 1,
    artist: "Ankit Tiwari",
    album: "Aashiqui 2",
    releaseDate: "3 months ago",
    src: "Songs/Sunn Raha Hai (Male).mp3",
  },
  {
    genre: "Hindi",
    image: "Song Images/Soch na sake.jpg",
    songName: "Soch Na Sake",
    songId: 2,
    artist: "Arijit Singh",
    album: "Airlift",
    releaseDate: "6 months ago",
    src: "Songs/Soch Na Sake Version 2 - Airlift (Arijit Singh) 320Kbps.mp3",
  },
  {
    genre: "Hindi",
    image: "Song Images/Kehdoon tumhe.jpg",
    songName: "Kehdoon Tumhe",
    songId: 3,
    artist: "Sanam",
    album: "Single",
    releaseDate: "6 months ago",
    src: "Songs/Deewar - Keh Doon Tumhe Ya Chup.mp3",
  },
  {
    genre: "Hindi",
    image: "Song Images/Ghar se nikalte hi.jpg",
    songName: "Ghar Se Nikalte",
    songId: 4,
    artist: "Armaan Malik",
    album: "Single",
    releaseDate: "6 months ago",
    src: "Songs/Ghar Se Nikalte Hi - Armaan Malik 320Kbps.mp3",
  },
  {
    genre: "Hindi",
    image: "Song Images/Lungi dance.jpg",
    songName: "Lungi Dance",
    songId: 5,
    artist: "Honey Singh",
    album: "Chennai Express",
    releaseDate: "6 months ago",
    src: "Songs/Lungi Dance - Chennai Express 320 Kbps.mp3",
  },
  {
    genre: "International",
    image: "Song Images/Hotel california.jpg",
    songName: "Hotel California",
    songId: 6,
    artist: "Eagles",
    album: "Hotel California",
    releaseDate: "3 months ago",
    src: "Songs/HotelCalifornia.mp3",
  },
  {
    genre: "International",
    image: "Song Images/Comfortably numb.jpg",
    songName: "Comfortably Numb",
    songId: 7,
    artist: "Pink Floyd",
    album: "The Wall",
    releaseDate: "6 months ago",
    src: "Songs/Comfortably Numb.mp3",
  },
  {
    genre: "International",
    image: "Song Images/Stairway to heaven.png",
    songName: "Stairway to Heaven",
    songId: 8,
    artist: "Led Zepellin",
    album: "The Song Remains the Same",
    releaseDate: "6 months ago",
    src: "Songs/StairwayToHeaven.mp3",
  },
  {
    genre: "International",
    image: "Song Images/Californication.jpg",
    songName: "Californication",
    songId: 9,
    artist: "Red Hot Chlli Peppers",
    album: "Californication",
    releaseDate: "6 months ago",
    src: "Songs/Californication.mp3",
  },
  {
    genre: "International",
    image: "Song Images/In the end.jpg",
    songName: "In The End",
    songId: 10,
    artist: "Linkin Park",
    album: "Hybrid Theory",
    releaseDate: "6 months ago",
    src: "Songs/In The End Best Song Download(SongsZilla.Net).mp3",
  },
  {
    genre: "Punjabi",
    image: "Song Images/wait1.jpg",
    songName: "Wait and Watch",
    songId: 11,
    artist: "Prem Dhillon",
    album: "Babbar",
    releaseDate: "3 months ago",
    src: "Songs/Wait  Watch - Prem Dhillon.mp3",
  },
  {
    genre: "Punjabi",
    image: "Song Images/desire1.jpg",
    songName: "Desire",
    songId: 12,
    artist: "AP Dhillon",
    album: "Single",
    releaseDate: "6 months ago",
    src: "Songs/Desires.mp3",
  },
  {
    genre: "Punjabi",
    image: "Song Images/sanju.jpg",
    songName: "Sanju",
    songId: 13,
    artist: "Sidhu Moosewala",
    album: "Single",
    releaseDate: "6 months ago",
    src: "Songs/Sanju Original.mp3",
  },
  {
    genre: "Punjabi",
    image: "Song Images/jawani.jpg",
    songName: "Jatt te Jawani",
    songId: 14,
    artist: "Dilpreet Dhillon",
    album: "Single",
    releaseDate: "6 months ago",
    src: "Songs/Jatt Te Jawani.mp3",
  },
  {
    genre: "Punjabi",
    image: "Song Images/u next.jpg",
    songName: "U Next",
    songId: 15,
    artist: "Prem Dhillon",
    album: "Single",
    releaseDate: "6 months ago",
    src: "Songs/U Next.mp3",
  },
];
